baseURL = ""
languageCode = "en-us"
title = "zpcknu - a newbie morty's blog"
theme = "zpcknu-theme"
MetaDataFormat = "toml"
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
PygmentsCodeFences = true
PygmentsStyle = "tango"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"
    about = "/:filename/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Live"
    url = "/posts/"
    weight = 2
[[menu.main]]
    name = "Notes"
    url = "/notes/"
    weight = 3
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 4
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 5

# My Own menu to list post For Fun.. Life
[[menu.mine]]
    name = "Oh Me! Oh Life!"
    url = "/lifes/"
    weight = 1
[params]
description = "A website built through Hugo and blogdown."
footer = "&copy; [Jason Yu](http://morty.tech/about/) 2017 -- 2018 | [Github](https://github.com/unkcpz) || FRIENDS LINKS:: [花草茶](https://changchunhe.github.io/) | [道长](https://shaobinqiu.github.io/)"
disqusShortname = "unkcpz"
